language: csharp
dist: trusty
env:
  - MONO_THREADS_PER_CPU=2000
mono:
  - 4.0.5
os:
  - linux
  - osx
solution: tarantool-dnx.sln

addons:
  apt:
    packages:
      - unzip
      - curl

before_install:
  - brew update
  - brew install curl

install:
  - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | sh && source ~/.dnx/dnvm/dnvm.sh && dnvm upgrade
  - dnvm update-self
  - dnvm upgrade
  - dnvm install 1.0.0-rc1-update1
  - dnvm list
  - dnvm use 1.0.0-rc1-update1
before_script:
  - dnu restore