version: 0.0.{build}
skip_tags: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

nuget:
  disable_publish_on_pr: true

configuration:
  - Release

matrix:
  fast_finish: false

clone_depth: 1

# build cache to preserve files/folders between builds
cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - '%LocalAppData%\NuGet\Cache'

init:
  - git config --global core.autocrlf true
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - ps: nuget sources add -Name api.nuget.org -Source https://api.nuget.org/v3/index.json

before_build:
  - nuget restore

on_finish:
- ps: $blockRdp = $true;

build:
  parallel: true
  project: TarantoolClient.sln
  verbosity: minimal

before_test:
  - ps: tarantool.cmd
 
deploy: off