variables:
  sln: progaudi.tarantool.sln
  tests: tests/progaudi.tarantool.tests/progaudi.tarantool.tests.csproj
  runDockerComposeBeforeTests: true

resources:
  repositories:
    - repository: templates
      type: github
      name: progaudi/azure-pipelines
      endpoint: progaudi

jobs:
- template: library/nuget.yml@templates
      